<div class="container_16 section clearfix">
    <div class="grid_16">
        <div class="pagination">
            <ul>
                <?php if($this->url() == $this->url(array(), 'dm-index')) : ?>
                    <li class="active"><a href="#">Inbox</a></li>
                    <?php else : ?>
                    <li><a href="<?php echo $this->url(array(), 'dm-index'); ?>">Inbox</a></li>
                <?php endif; ?>
                
                <?php if($this->url() == $this->url(array(), 'dm-sent')) : ?>
                    <li class="active"><a href="#">Sent Items</a></li>
                    <?php else : ?>
                    <li><a href="<?php echo $this->url(array(), 'dm-sent'); ?>">Sent Items</a></li>
                <?php endif; ?>
                <li class="disabled"><a href="#"> Page &rarr;</a></li>
                <?php for($i=1; $i<=17; ++$i):?>
                    <?php if($this->url() == $this->url(array('page' => $i))) : ?>
                        <li class="active"><a href="#"><?php echo $i;?></a></li>
                    <?php else:?>
                        <li><a href="<?php echo $this->url(array('page' => $i));?>"><?php echo $i;?></a></li>
                    <?php endif; ?>
                <?php endfor;?>
            </ul>
        </div>
    </div>
</div>