<div class="container_16 section clearfix">
    <div class="grid_4"> 
        <div class="box">
            <?php $tweet = $this->tweet; ?>
            <?php $user  = $tweet->user; ?>

            <?php echo $this->profPict($user->profile_image_url, $user->screen_name); ?>
            
            <ul class="tweet_detail">
                <li><a href="<?php echo $this->url(array('screen_name' => $user->screen_name), 'index-show_user'); ?>"><i class="icon-user"></i> <?php echo sprintf("%s (@%s)", $user->name, $user->screen_name)?></a></li>
                <li><i class="icon-calendar"></i> Join <?php echo date("j/M/Y", strtotime($user->created_at)); ?></li>
                <li><i class="icon-list-alt"></i> <strong><?php echo $user->followers_count; ?></strong> followers</li>
            </ul>
            <div class="clearfix"></div>

            <ul class="tweet_menu">
                <li><i class="icon-tag"></i> <?php echo $user->friends_count; ?> friends</li>
                <li><i class="icon-check"></i> <?php echo $user->statuses_count; ?> tweets</li>
                <li><i class="icon-heart"></i> <?php echo $user->favourites_count; ?> favs</li>
            </ul>
            
            <span style="font-weight: bold;">TweetID </span><?php echo $tweet->id; ?>
            <p class="tweet_single"><?php echo $this->tweetFilter($tweet->text); ?></p>

            <ul class="tweet_menu">
                <li><i class="icon-flag"></i> via <?php echo $tweet->source; ?></li>
            </ul>

        </div>
    </div>
    <div class="grid_12">
        <div class="box">
            <?php echo str_replace(array('{{', '}}', '||'), array('<','>', '"'), $this->form->setAction($this->url())); ?>
        </div>
        
    </div>
</div>
