<div id="section" style="min-height: 300px !important;padding-bottom: 0 !important;">
    <div class="container_16 section clearfix">
        <div class="grid_6 prefix_5">
            <p style="text-align: center;">
                <strong>HELLO GUEST</strong> <br />
                Welcome to <?php echo $this->twitterOption('app_name'); ?>. I&#39;m a private Twitter client, sign in to use me further more. <br /><br />
                <a href="<?php echo $this->url(array(), 'oauth-login'); ?>">
                    <img alt="Sign in with Twitter" src="/assets/img/sign-in-with-twitter-l.png" style="margin-top: 15px; width:151px;height:24px;">
                </a>
            </p>
        </div>
        
    </div>
</div>