<?php $loggedIn = Service_Twitter::getInstance()->getTwitter()->isAuthorised(); ?>
<?php echo $this->docType(); ?>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <!--[if IE]>
        <meta content='IE=10; IE=9' http-equiv='X-UA-Compatible'/>
        <style type="text/css"> .gradient { filter: none; }</style>
    <![endif]-->
    <?php $this->headLink()->prependStylesheet('/assets/css/base.css?v=' . md5('v1')); ?>
    <?php $this->headLink()->appendStylesheet('/assets/css/app.css?v=' . md5('v4')); ?>
    <?php $this->headLink(array('rel' => 'shortcut icon', 'href' => '/assets/img/favicon.ico', 'type' => 'image/x-icon'), 'PREPEND'); ?>
    <?php $this->headTitle($this->twitterOption('app_name'))->setSeparator(' / '); ?>
    
    <?php echo $this->headMeta(); ?>
    <?php echo $this->headTitle(); ?>
    <?php echo $this->headLink(); ?>
    <?php echo $this->headStyle(); ?>
</head>
<body class="simukti<?php echo $loggedIn ? '' : ' guest'; ?>">

    <?php if($loggedIn) : /* displayed only for logged in user */ ?>
    
        <div id="header">
            <div class="container_16 clearfix">
                <div class="grid_5">
                    <h1 class="site_title"><a href="/"><?php echo $this->twitterOption('app_name'); ?></a></h1>
                </div>
                
                <div class="grid_11">
                    <?php echo str_replace(array('{{', '}}', '||'), array('<','>', '"'), $this->navigation()->menu()->setUlClass('navigation')->setMaxDepth(0)->renderMenu()); ?>
                </div>
            </div>
        </div>
        
        <div id="section">
            <?php echo $this->layout()->content; ?>
        </div>
        
        <div id="footer">
            <div class="container_16 clearfix footer">
                <div class="grid_8">
                    <p><?php echo $this->twitterOption('app_name'); ?> &middot; Copyright &copy; <?php echo date('Y') == 2011 ? date('Y') : sprintf("2011 - %s", date('Y'));?> <a href="http://simukti.net/" target="_blank">Sarjono Mukti Aji</a> &middot; Powered by <a href="http://framework.zend.com/" target="_blank">ZendFramework v<?php echo Zend_Version::VERSION; ?></a></p>
                </div>
            </div>
        </div>
        
        <script type="text/javascript">
            (function(){
                var forms = document.forms || [];
                for(var i = 0; i < forms.length; i++){
                    for(var j = 0; j < forms[i].length; j++){
                        if(!forms[i][j].readonly != undefined && forms[i][j].type != "hidden" && forms[i][j].disabled != true && forms[i][j].style.display != 'none'){
                            forms[i][j].focus();
                            return;
                        }
                    }
                }
            })();
        </script>
        
    <?php else: ?>
        <!-- custom welcome page should be placed here -->
        <?php echo $this->render('_guest.phtml');?>
    <?php endif;?>
    
    <script type="text/javascript">
        WebFontConfig = { google: { families: [ 'Droid+Sans:400,700:latin' ] } };
        (function() {
            var wf = document.createElement('script');
            wf.src = '//ajax.googleapis.com/ajax/libs/webfont/1/webfont.js';
            wf.type = 'text/javascript'; wf.async = 'true';
            var s = document.getElementsByTagName('script')[0];
            s.parentNode.insertBefore(wf, s);
        })(); 
    </script>
</body></html>